### ISSUE TITLE
64 bit suport?

### ISSUE THREAD

**Issue by amwinsauto** [benbahrenburg/Ti.iSpeech#2]
Is there any way you could possibly upgrade this for x64 bit to satisfy the new Apple requirement?

Thank you!
Adam.

**Comment by benbahrenburg** [comment]
updated to the latest framework

**Comment by amwinsauto** [comment]
I tried using v0.2 in my app "DASH" and am getting the following error:
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/DASH.build/Debug-iphoneos/DASH-iPad.build/Objects-normal/arm64/DASH normal arm64
[ERROR] :  (1 failure)

I am using Ti 3.5.0.GA.

**Comment by benbahrenburg** [comment]
At the moment there is an issue related to the iSpeech SDK not being 64 compatible.

**Comment by rsinghcharan** [comment]
I am also facing the same issue it also showing me this error for my "appname":
Ld build/appname.build/Debug-iphonesimulator/appname-universal.build/Objects-normal/x86_64/appname normal x86_64

I am also using 3.5.0 SDK with version 0.2.

**Comment by benbahrenburg** [comment]
Unfortunately iSpeech didn't release an SDK which is compatible.  I would encourage you to reach out to them and ask them to add both Simulator and 64x support to their SDK.

**Comment by benbahrenburg** [comment]
iSpeech just updated their SDK to provide support for both the simulator and x64.  Version v04 of the module now is working as expected.
