### ISSUE TITLE
Installing module in Titanium fails

### ISSUE THREAD

**Issue by onelifemedia** [benbahrenburg/Ti.iSpeech#3]
I'm using 3.5.0.GA.  I installed the module using Titanium Studio, and manually from the command line.  I verified that I `cp -R modules/iphone/ti.ispeech/0.2/platform/ platform/`

As soon as I tried to add the module in the TiApp Editor, and do a build, I get this message:

```
[ERROR] :  2015-03-07 09:02:06.766 xcodebuild[90704:5b03]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/fartfartfart/Library/Developer/Xcode/DeveloperPortal%206.1.1.db).
[ERROR] :  ** BUILD FAILED **
```

Any help would be greatly appreciated.

**Comment by benbahrenburg** [comment]
Correct, the latest version of the iSpeech SDK does not support 64x

**Comment by onelifemedia** [comment]
Thanks.

This is the first time that I'm using Titanium, and I thought that I was doing something wrong.  Perhaps I should read the instructions.

**Comment by benbahrenburg** [comment]
I would encourage you to ask contact ispeech (https://www.ispeech.org/developers/iphone) and ask them to provide support for both 64x and simulator compile options. This will allow for the module to work correctly

**Comment by benbahrenburg** [comment]
iSpeech just updated their SDK to provide support for both the simulator and x64.  Version v04 of the module now is working as expected.
